#!/usr/bin/env python3
"""Start a new property build from a floor-plan image (one command).

Init:
    python3 new_property.py --plan PATH.png --id PROPERTY_ID --name "Display name" \\
        (--width-ft W --depth-ft D | --width-m W --depth-m D) \\
        [--work-root DIR] [--ceiling 2.44] \\
        [--market "USA, USD, US retailers"] [--currency USD] \\
        [--style "exterior ...; interior ..."] [--storeys 1] [--crop x0,y0,x1,y1] [--force]

Status / spec check:
    python3 new_property.py --status PROPERTY_ID [--work-root ...]
    python3 new_property.py --check-spec PROPERTY_ID [--work-root ...]

Init creates <work-root>/<id>/ with source/ (a copy of the plan), research/ gen/ payloads/
validation/ renders/ review/, and writes:
  spec.draft.json, spec-overlay.png   measure/measure_plan.py output (review it, save as spec.json)
  plan.md                             templates/PLAN-TEMPLATE.md with every measurable placeholder filled
  areas.json                          generic role-based areas (tailor to the rooms the plan has)
  create_property.draft.json          create_property arguments (rooms still to fill)
  build-args.json                     args for workflow/build.js and workflow/review.js
  MANUAL-EDITS.md, STATUS.md          edit log header and the remaining-steps checklist

--work-root defaults to $PROPERTY_BUILD_WORK_ROOT, else ~/property-build-work. It must persist
between sessions: in a hosted session whose home folder is wiped, use the project's shared files.

Python 3.9+, standard library plus Pillow (for the plan measurer).
"""
import argparse
import datetime
import json
import math
import os
import re
import shutil
import subprocess
import sys

from lib.polygons import clip_rect, strips
from lib.schema_check import Validator

KIT = os.path.dirname(os.path.abspath(__file__))
FT = 0.3048
HOME_ROOT = os.path.expanduser('~/property-build-work')
# PROPERTY_BUILD_WORK_ROOT overrides the default where the home folder is not kept between sessions
# (hosted or cloud sessions): point it at a folder that persists, such as a project's shared files.
DEFAULT_ROOT = os.path.abspath(os.path.expanduser(os.environ.get('PROPERTY_BUILD_WORK_ROOT') or HOME_ROOT))
SUBDIRS = ('source', 'research', 'gen', 'payloads', 'validation', 'renders', 'review')
ID_RE = re.compile(r'^[a-z0-9](?:[a-z0-9]|-(?=[a-z0-9])){1,58}[a-z0-9]$')
PH_RE = re.compile(r'\{\{([^{}]*)\}\}')
TEMP_PREFIXES = ('/tmp', '/private/tmp', '/var/folders', '/private/var/folders')


def die(msg, code=2):
    sys.stderr.write('new_property: %s\n' % msg)
    sys.exit(code)


def durable_or_die(path):
    """Refuse temp and scratchpad directories: working files there were wiped mid-build before."""
    for p in {os.path.abspath(path), os.path.realpath(path)}:
        for pre in TEMP_PREFIXES:
            if p == pre or p.startswith(pre + '/'):
                die('work root %s is a temp directory (%s). Use a durable folder such as %s.' % (path, pre, HOME_ROOT))
        if 'scratchpad' in p:
            die('work root %s is a scratchpad directory. Use a durable folder such as %s.' % (path, HOME_ROOT))


def write_json(path, obj):
    with open(path, 'w') as f:
        json.dump(obj, f, indent=1)
        f.write('\n')


def load_json(path):
    with open(path) as f:
        return json.load(f)


def fmt_m(v):
    return ('%.3f' % v).rstrip('0').rstrip('.')


# --------------------------------------------------------------------------- generic areas
def generic_areas(style, market):
    """Role-based starting areas. Scopes refer to spec.json entries by role, never by coordinates."""
    return {
        '_note': ('Starting areas generated by new_property.py. Tailor them to the rooms this plan actually has, '
                  'then delete every "_todo". Fields: key (folder and owner name), prefix (unique id prefix ending '
                  'in -), title, lights (real light sources; the total should fit lightBudget), research (what kinds '
                  'of items to find, in the market: %s), scope (what to model and what to keep clear). Scopes name '
                  'spec.json entries (rooms, drawnItems, outerWalls/interiorWalls openings); never type coordinates: '
                  'spec.json is authoritative.' % market),
        'areas': [
            {
                'key': 'exterior', 'prefix': 'ex-', 'title': 'Exterior', 'lights': 3,
                'research': ('exterior wall lights for each exterior door, an entrance or porch ceiling light, '
                             'entrance door hardware, house numbers, outdoor planters and plants that suit the '
                             'climate; a roofing product and a cladding product for the shopping notes'),
                'scope': ('Roof over the whole spec.json footprint in a form that suits the exterior style (%s): roof '
                          'covering as instanced courses or panels, eaves, soffits, fascia, gutters and downpipes, '
                          'and any gable or parapet infill between the ceiling and the roof. Cladding on the outside '
                          'faces of spec.outerWalls with every opening left clear; a plinth from spec.grade.y to y=0; '
                          'exterior window and door casings. An entrance step or porch at the main entrance door in '
                          'spec.outerWalls, and a step at every other exterior door. Ground plane at grade around the '
                          'house, a path to the entrance, planting. Exterior lights with real light sources. Roof, '
                          'soffit, infill and porch-roof nodes use behavior cutaway hide and no collision. Nothing '
                          'inside the footprint.' % (style or 'see spec.json style')),
                '_todo': 'Choose the roof form and whether there is a porch from the plan and style; drop the porch '
                         'if the entrance has none.',
            },
            {
                'key': 'finishes', 'prefix': 'fl-', 'title': 'Floors and finishes', 'lights': 0,
                'research': ('a dry-room floor finish (plank, engineered wood, laminate or similar), a wet-room floor '
                             'tile, a wall tile for wet areas, the main wall paint and an accent colour, a skirting '
                             'and door casing profile'),
                'scope': ('Floor finish in every dry room in spec.rooms (instanced planks or tiles a few mm thick at '
                          'y 0.000-0.003, no collision, raycast false); tile with a darker grout underlay in each wet '
                          'room (bathrooms, laundry, utility), tops >= 2 mm apart. Skirting along every interior wall '
                          'face, skipping door openings and the runs behind built-ins in spec.drawnItems. Casings on '
                          'both faces of every interior opening. A ceiling per room at the ceiling height (cutaway '
                          'hide, raycast false, no collision). At most one accent wall. No finishes outside the '
                          'footprint.'),
            },
            {
                'key': 'kitchen', 'prefix': 'kt-', 'title': 'Kitchen', 'lights': 3,
                'research': ('base and wall cabinets from one real cabinet line, a worktop, a backsplash, a cooker or '
                             'hob and oven, an extractor hood, a fridge, a dishwasher, a sink and tap, bar stools if '
                             'there is an island or peninsula, pendant or ceiling lights'),
                'scope': ('The kitchen room or zone in spec.rooms: cabinet runs along the kitchen run(s) in '
                          'spec.drawnItems, with each appliance and the sink at its drawn item where one is drawn '
                          '(otherwise a sensible position on the run, recorded as an assumption). Wall cabinets above '
                          'the runs except over windows, a hood over the cooker. An island or peninsula only if '
                          'spec.drawnItems has one, with seating if it overhangs. Ceiling or pendant lights with real '
                          'light sources. Keep >= 1.0 m between facing runs and every doorway in spec.interiorWalls '
                          'and spec.outerWalls next to the kitchen clear.'),
                '_todo': 'Keep if the plan has a kitchen; if it is a small part of an open room, consider merging it '
                         'into living. Name the kitchen drawn items here once spec.json has them.',
            },
            {
                'key': 'living', 'prefix': 'lv-', 'title': 'Living and dining', 'lights': 3,
                'research': ('a sofa sized to the room, a coffee table, accent chairs, an area rug, a media unit and '
                             'TV, a floor lamp, curtains or blinds and rods, framed art, plants, a dining table and '
                             'chairs for the space, a dining pendant'),
                'scope': ('Every living, family and dining room or zone in spec.rooms: seating at the drawn sofa and '
                          'chair items in spec.drawnItems where drawn, a rug under the seating group, media unit, '
                          'lamp, window dressings on the windows of those rooms (spec.outerWalls openings), art '
                          '(layers >= 2 mm apart), plants. Dining table and chairs centred in the dining zone with a '
                          'pendant (real light source). Items not drawn on the plan are proposed additions, recorded '
                          'as assumptions. Keep a clear route from the entrance to every door and the kitchen, and '
                          'keep every door swing clear.'),
                '_todo': 'Drop the dining part if the plan has no dining space; split into two areas if living and '
                         'dining are separate rooms far apart.',
            },
            {
                'key': 'bedrooms', 'prefix': 'br-', 'title': 'Bedrooms', 'lights': 3,
                'research': ('beds sized to each bedroom (a different style per room), bedding, nightstands, table '
                             'lamps, rugs, a dresser or chest, a desk and chair for one room, wardrobe or closet '
                             'fittings (rail and shelf or a system), curtains, ceiling lights'),
                'scope': ('Each bedroom room in spec.rooms, and each closet room that opens off one: beds at the bed '
                          'items in spec.drawnItems (headboard against the wall it is drawn on, below the sill if a '
                          'window is behind it), nightstands at their drawn items, lamps, rugs, storage on a free wall '
                          'clear of door and closet swings, window dressings, one ceiling light per bedroom. Closets: '
                          'rail and shelf, walkways >= 0.6 m in walk-ins. Keep every door leaf and bifold in '
                          'spec.interiorWalls clear.'),
                '_todo': 'Set lights to the number of bedrooms. Split into a main-bedroom area and an other-bedrooms '
                         'area if there are more than three bedrooms or a large walk-in closet.',
            },
            {
                'key': 'bathrooms', 'prefix': 'ba-', 'title': 'Bathrooms', 'lights': 2,
                'research': ('a bath and/or shower tray and enclosure that fit the drawn space, bath/shower taps, a '
                             'toilet, a vanity unit and basin tap, a mirror, a vanity or ceiling light, towel rails'),
                'scope': ('Each bathroom, en-suite and WC room in spec.rooms: bath, shower, toilet and vanity at their '
                          'drawn items in spec.drawnItems, tiled surround on the walls around the bath or shower (tile '
                          'and grout layers >= 2 mm apart), taps and shower head, mirror and a light with a real light '
                          'source per room. Keep each door leaf clear of the fixtures.'),
                '_todo': 'Set lights to the number of bathrooms; split per bathroom if there are more than two.',
            },
            {
                'key': 'utility', 'prefix': 'ut-', 'title': 'Laundry and utility', 'lights': 1,
                'research': ('a washing machine and dryer (or washer-dryer) that fit the drawn space, utility '
                             'shelving or cabinets, a utility sink if drawn, a ceiling light'),
                'scope': ('The laundry, utility, pantry and storage cupboard rooms in spec.rooms: appliances at their '
                          'drawn items in spec.drawnItems, shelving above them, shelving behind cupboard bifolds, a '
                          'light with a real light source. Keep the exterior door and every interior doorway into '
                          'these rooms clear.'),
                '_todo': 'Drop this area if the plan has no laundry, utility or storage rooms; otherwise list them '
                         'here.',
            },
        ],
    }


# --------------------------------------------------------------------------- measurement helpers
def entrance_from_spec(spec):
    """(point, opening, todo) for a point 0.4 m inside the main exterior door, else the footprint centre."""
    W, D = spec['footprint']
    doors = []
    for w in spec.get('outerWalls', []):
        for o in w.get('openings', []):
            if o.get('type') == 'door':
                score = (bool(o.get('entrance')) or 'front' in o.get('id', ''),
                         o.get('swingSide') == 'interior', o['to'] - o['from'])
                doors.append((score, w, o))
    if not doors:
        return [round(W / 2, 3), round(D / 2, 3)], None, True
    doors.sort(key=lambda t: t[0], reverse=True)
    _, w, o = doors[0]
    mid = (o['from'] + o['to']) / 2.0
    if w['axis'] == 'x':
        inner = w['inner_z']
        sign = 1 if inner > w['line_z_outer'] else -1
        pt = [mid, inner + 0.4 * sign]
    else:
        inner = w['inner_x']
        sign = 1 if inner > w['line_x_outer'] else -1
        pt = [inner + 0.4 * sign, mid]
    return [round(pt[0], 3), round(pt[1], 3)], (w['id'], o['id']), False


def agreement_pct(mx, mz):
    return abs(mx - mz) / ((mx + mz) / 2.0) * 100.0


def openings_list(spec):
    out = []
    for w in spec.get('outerWalls', []) + spec.get('interiorWalls', []):
        for o in w.get('openings', []):
            out.append((w['id'], o))
    return out


# --------------------------------------------------------------------------- plan.md
def render_plan(tpl, ctx, areas):
    """Fill the template; return (text, unfilled placeholder list)."""
    # Replace the template's leading author comment with a generated note.
    tpl = re.sub(r'<!--.*?-->\n*', '', tpl, count=1, flags=re.S)
    tpl = tpl.replace('`~/property-build-work/{{PROPERTY_ID}}/`', '`%s/`' % ctx['WORKDIR'])
    # The area table row: expand from areas.json.
    rows = []
    for a in areas['areas']:
        scope = a['scope']
        if len(scope) > 160:
            scope = scope[:157].rsplit(' ', 1)[0] + ' ...'
        rows.append('| %s | `%s` | %s | %s |' % (a['title'], a['prefix'], a['lights'], scope.replace('|', '/')))
    tpl = re.sub(r'^\| \{\{AREA\}\} \|.*$', '\n'.join(rows), tpl, count=1, flags=re.M)

    def sub(m):
        inner = m.group(1)
        key = inner.split(',')[0].strip()
        if key in ctx and ctx[key] is not None:
            return str(ctx[key])
        if inner.startswith('production | local'):
            return 'production'
        if inner.startswith('single storey') and ctx.get('_storeys', 1) == 1:
            return 'single storey: do NOT set a floors list'
        return m.group(0)

    text = PH_RE.sub(sub, tpl)
    left = sorted(set('{{%s}}' % p for p in PH_RE.findall(text)) - {'{{PLACEHOLDER}}'})
    header = ('<!-- Generated by the build-property kit (new_property.py) on %s. Measured values come from '
              'spec.draft.json; spec.json is authoritative once reviewed. Still to fill: %s. Delete this comment '
              'when done. -->\n\n' % (ctx['TODAY'], ', '.join(left) if left else 'nothing'))
    lines = text.split('\n', 1)
    text = lines[0] + '\n\n' + header + (lines[1].lstrip('\n') if len(lines) > 1 else '')
    return text, left


# --------------------------------------------------------------------------- init
STATUS_ITEMS = [
    ('spec', 'review spec-overlay.png against the plan; fill spec rooms, drawnItems, hinge/swing, sill heights '
             '-> save as spec.json (validate: `new_property.py --check-spec {id}`)'),
    ('plan', 'fill plan.md placeholders; tailor areas.json (remove every "_todo", copy into build-args.json areas)'),
    ('create', 'create_property (create_property.draft.json + rooms; drop "_"-keys; save rooms to rooms.json) ; '
               'publish lib/materials.json ; set startRevision in build-args.json'),
    ('viewer', 'open the signed-in viewer tab'),
    ('build', 'run workflow/build.js ; run workflow/review.js ; walkthrough + VR ; extract new products'),
]



# Model per workflow role (args.models). A value is a tier ("strong", "standard", "fast"), a model name, or
# {"model", "effort"}; "role.<areaKey>" overrides one area. Roles left out use the session's model. The host
# maps tiers to its models (Claude Code: Opus, Sonnet, Haiku). Strong where quality shows in the result
# (modelling, visual critique, fixes); standard for research, checks and settings; fast for mechanical work.
DEFAULT_MODELS = {
    'research': {'model': 'standard', 'effort': 'medium'},
    'shell-model': {'model': 'standard', 'effort': 'medium'},
    'shell-check': {'model': 'standard', 'effort': 'medium'},
    'modeller': {'model': 'strong', 'effort': 'high'},
    'modeller.finishes': {'model': 'standard', 'effort': 'medium'},
    'modeller.exterior': {'model': 'standard', 'effort': 'high'},
    'writer': {'model': 'standard', 'effort': 'low'},
    'checker': {'model': 'standard', 'effort': 'medium'},
    'verify': {'model': 'standard', 'effort': 'low'},
    'lighting': {'model': 'standard', 'effort': 'medium'},
    'access-points': {'model': 'standard', 'effort': 'low'},
    'renderer': {'model': 'fast', 'effort': 'low'},
    'critic': {'model': 'strong', 'effort': 'high'},
    'fixer': {'model': 'strong', 'effort': 'high'},
    'final': {'model': 'standard', 'effort': 'low'},
}

def cmd_init(a):
    if not a.plan or not a.name:
        die('--plan and --name are required with --id')
    if not ID_RE.match(a.id):
        die('--id must be 3-60 lowercase letters, numbers and single hyphens, starting and ending with a letter or '
            'number (it cannot be changed later)')
    if bool(a.width_ft) != bool(a.depth_ft) or bool(a.width_m) != bool(a.depth_m) or \
            bool(a.width_ft) == bool(a.width_m):
        die('give exactly one pair: --width-ft W --depth-ft D, or --width-m W --depth-m D (labelled outside size)')
    if not os.path.isfile(a.plan):
        die('plan image not found: %s' % a.plan)
    if a.storeys < 1:
        die('--storeys must be >= 1')
    root = os.path.abspath(os.path.expanduser(a.work_root))
    durable_or_die(root)
    work = os.path.join(root, a.id)
    if os.path.exists(work) and not a.force:
        die('%s already exists; pass --force to regenerate its generated files (spec.json, rooms.json, research, '
            'payloads and logs are kept)' % work)
    try:
        from PIL import Image
    except ImportError:
        die('Pillow is required for the plan measurer. Install it with: python3 -m pip install Pillow '
            '(add --user, or --break-system-packages on an externally managed Python, if that is refused)')

    for d in SUBDIRS:
        os.makedirs(os.path.join(work, d), exist_ok=True)
    plan_name = os.path.basename(a.plan)
    plan_copy = os.path.join(work, 'source', plan_name)
    if os.path.abspath(a.plan) != plan_copy:
        shutil.copy2(a.plan, plan_copy)
    with Image.open(plan_copy) as im:
        img_w, img_h = im.size

    if a.width_ft:
        width_m, depth_m = a.width_ft * FT, a.depth_ft * FT
        dims = '%s ft x %s ft = %.2f m x %.2f m' % (fmt_m(a.width_ft), fmt_m(a.depth_ft), width_m, depth_m)
        label = '%s ft x %s ft' % (fmt_m(a.width_ft), fmt_m(a.depth_ft))
    else:
        width_m, depth_m = a.width_m, a.depth_m
        dims = '%.2f m x %.2f m (%.1f ft x %.1f ft)' % (width_m, depth_m, width_m / FT, depth_m / FT)
        label = '%s m x %s m' % (fmt_m(width_m), fmt_m(depth_m))

    # 3. measure
    draft_path = os.path.join(work, 'spec.draft.json')
    overlay = os.path.join(work, 'spec-overlay.png')
    cmd = [sys.executable, os.path.join(KIT, 'measure', 'measure_plan.py'), plan_copy,
           '--property-id', a.id, '--source-file', 'source/' + plan_name, '--ceiling', str(a.ceiling),
           '--out', draft_path, '--debug-png', overlay]
    cmd += ['--width-ft', str(a.width_ft), '--depth-ft', str(a.depth_ft)] if a.width_ft else \
        ['--width-m', str(a.width_m), '--depth-m', str(a.depth_m)]
    if a.crop:
        cmd += ['--crop', a.crop]
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode != 0:
        die('measure_plan.py failed:\n%s%s' % (r.stdout, r.stderr), 1)
    measure_out = r.stdout.strip()
    spec = load_json(draft_path)

    # Extra keys the rest of the kit reads; the reviewer completes them.
    ext_style = None
    if a.style:
        ext_style = re.sub(r'^(exterior|interior)\b\s*:?\s*', '', a.style.split(';', 1)[0].strip(), flags=re.I)
    areas = generic_areas(ext_style, a.market)
    spec['idPrefixes'] = dict([('shell-outer', 'so-'), ('shell-inner', 'si-')] +
                              [(x['key'], x['prefix']) for x in areas['areas']] +
                              [('lighting', 'lt-'), ('library', 'm-')])
    if a.style:
        parts = [re.sub(r'^(exterior|interior)\b\s*:?\s*', '', p.strip(), flags=re.I) for p in a.style.split(';', 1)]
        spec['style'] = {'exterior': parts[0], 'interior': parts[1] if len(parts) > 1 else parts[0]}
    spec['grade'] = {'y': -0.3, 'note': 'Assumed: finished floor y=0, outside ground y=-0.30. Check against the plan.'}
    spec.setdefault('review', []).append('grade.y -0.30 is an assumption: set the real step from ground to floor.')
    if a.storeys > 1:
        spec['review'].append('--storeys %d: this draft measures one storey only; measure each level separately '
                              'and add a floors list.' % a.storeys)
    write_json(draft_path, spec)

    src = spec['source']
    fp = src['footprintPx']
    mx, mz = src['metresPerPixel']['x'], src['metresPerPixel']['z']
    agree = agreement_pct(mx, mz)
    OT, IT = spec['wallThickness']['outer'], spec['wallThickness']['interior']
    entrance, ent_door, ent_todo = entrance_from_spec(spec)
    today = datetime.date.today().isoformat()

    # 5. areas
    areas_path = os.path.join(work, 'areas.json')
    write_json(areas_path, areas)

    # 4. plan.md
    ctx = {
        'PROPERTY_TITLE': a.name, 'PROPERTY_ID': a.id, 'PLAN_FILE': 'source/' + plan_name,
        'OVERALL_DIMENSIONS': dims, 'W': img_w, 'H': img_h, 'FW': fp['widthPx'], 'FH': fp['heightPx'],
        'LEFT': fp['left'], 'TOP': fp['top'],
        'M_PER_PX': '%.6f (x) / %.6f (z)' % (mx, mz), 'AGREEMENT': '%.2f' % agree,
        'CORNER': 'top-left (north-west)', 'OUTER_T': fmt_m(OT), 'INNER_T': fmt_m(IT),
        'CEILING': '%.2f m (%.1f ft)' % (a.ceiling, a.ceiling / FT),
        'CURRENCY and retailers': a.market if a.currency in a.market else '%s (%s)' % (a.market, a.currency),
        'GRADE': '%.2f (assumed: confirm)' % spec['grade']['y'],
        'MAX_CHECK_ROUNDS': 3, 'REVIEW_ROUNDS': 2,
        'EXTERIOR STYLE': spec.get('style', {}).get('exterior'),
        'INTERIOR STYLE': spec.get('style', {}).get('interior'),
        'WORKDIR': work, 'TODAY': today, '_storeys': a.storeys,
    }
    with open(os.path.join(KIT, 'templates', 'PLAN-TEMPLATE.md')) as f:
        tpl = f.read()
    plan_md, plan_left = render_plan(tpl, ctx, areas)
    plan_path = os.path.join(work, 'plan.md')
    with open(plan_path, 'w') as f:
        f.write(plan_md)

    # 6. create_property draft
    scale_basis = ('Labelled outside dimensions %s (%.3f m x %.3f m). On the supplied plan (%d x %d px) the outer '
                   'footprint spans %d x %d px (left %d, top %d): %.6f m/px along x and %.6f m/px along z, agreeing '
                   'within %.2f%%. Origin at the outside north-west corner, +x east (plan right), +z south (plan '
                   'down).' % (label, width_m, depth_m, img_w, img_h, fp['widthPx'], fp['heightPx'], fp['left'],
                               fp['top'], mx, mz, agree))
    h = spec['heights']
    assumptions = [
        'Ceiling height %.2f m (%.1f ft), from the build brief rather than the plan.' % (a.ceiling, a.ceiling / FT),
        'Wall thicknesses taken from the drawn line weights: outer %.3f m, interior %.3f m.' % (OT, IT),
        'Door heads %.3f m; window sills %.3f m and heads %.3f m unless the plan shows otherwise (standard '
        'defaults, not on the plan).' % (h['door'], h['windowSill'], h['windowHead']),
        'Wall positions and openings are read from drawn line thickness; drawn thickness may differ from built '
        'thickness by a few centimetres.',
        'Finished floor y = 0; outside ground y = -0.30 m (assumed).',
    ]
    if ent_todo:
        assumptions.append('Entrance point at the footprint centre: no exterior door was detected on the plan.')
    else:
        assumptions.append('Entrance 0.4 m inside the exterior door %s on the %s wall.' % (ent_door[1], ent_door[0]))
    create = {
        '_todo': ['rooms: fill from spec.json rooms (id, name, center [x,z]; accessPoint optional, corrected after '
                  'furnishing). create_property requires at least one room.',
                  'Check the entrance point lies on clear floor inside the footprint.',
                  'Remove every key starting with "_" before calling mcp__PropertyPrompt__create_property.'],
        'id': a.id, 'name': a.name, 'currency': a.currency, 'ceilingHeight': a.ceiling,
        'floorPolygons': [[[0, 0], [round(width_m, 3), 0], [round(width_m, 3), round(depth_m, 3)],
                           [0, round(depth_m, 3)]]],
        'entrance': entrance,
        'rooms': [],
        'authoring': {
            'source': 'Supplied floor plan %s (%d x %d px), labelled %s outside.' % (plan_name, img_w, img_h, label),
            'scaleBasis': scale_basis,
            'assumptions': assumptions,
        },
    }
    if ent_todo:
        create['_todo'].insert(1, 'entrance: no exterior door detected; footprint centre used. Set a point just '
                                  'inside the main door.')
    if a.storeys > 1:
        create['_todo'].append('--storeys %d: add a floors list (each level its own footprint, elevation, entrance) '
                               'and stairs.' % a.storeys)
    write_json(os.path.join(work, 'create_property.draft.json'), create)

    # 7. build args
    args = {
        'propertyId': a.id, 'workDir': work, 'kitDir': KIT, 'planImage': plan_copy, 'brief': plan_path,
        'productsDir': os.path.abspath(os.path.expanduser(os.environ.get('PROPERTY_BUILD_PRODUCTS') or os.path.join(root, 'products'))),
        'today': today, 'market': a.market,
        'style': a.style or 'see spec.json style',
        'lightBudget': 15, 'maxCheckRounds': 3, 'shellCheckRounds': 3, 'lightingCheckRounds': 2,
        'reviewRounds': 2, 'fixCheckRounds': 2,
        'models': DEFAULT_MODELS,
        'skip': {'research': False, 'shell': False, 'lighting': False, 'areas': []},
        'knownNonIssues': [], 'cameras': None,
        'startRevision': None,
        'areas': areas,
    }
    write_json(os.path.join(work, 'build-args.json'), args)

    # 8. MANUAL-EDITS.md and STATUS.md
    me = os.path.join(work, 'MANUAL-EDITS.md')
    if not os.path.exists(me):
        with open(me, 'w') as f:
            f.write('# %s: manual edits\n\nEvery write to `%s` made outside the build/review workflows (main '
                    'session, browser), with the revisions before and after. Workflows never run while these '
                    'happen.\n\n| Date | Revision | Tool | What | Why |\n|---|---|---|---|---|\n' % (a.name, a.id))
    todos = []
    todos += ['plan.md: %s' % p for p in plan_left]
    todos += ['areas.json %s: %s' % (x['key'], x['_todo']) for x in areas['areas'] if x.get('_todo')]
    todos += ['create_property.draft.json: %s' % t for t in create['_todo'][:-1]]
    if not a.style:
        todos.append('style: none given; set spec.json style and build-args.json style.')
    with open(os.path.join(work, 'STATUS.md'), 'w') as f:
        f.write('# %s (`%s`): build status\n\nGenerated %s by new_property.py. Run `python3 %s --status %s%s` to '
                'see what is done. Tick manual items here.\n\n' % (
                    a.name, a.id, today, os.path.join(KIT, 'new_property.py'), a.id,
                    '' if root == HOME_ROOT else ' --work-root %s' % root))
        for _, text in STATUS_ITEMS:
            f.write('- [ ] %s\n' % text.format(id=a.id))
        f.write('\n## Open TODOs\n\n' + ''.join('- %s\n' % t for t in todos))
        f.write('\n## Measurement review items (spec.draft.json review)\n\n' +
                ''.join('- %s\n' % t for t in spec.get('review', [])))

    # 9. summary
    print('Property %s (%s) in %s' % (a.id, a.name, work))
    print('\nWritten:')
    for p in ['source/' + plan_name, 'spec.draft.json', 'spec-overlay.png', 'plan.md', 'areas.json',
              'create_property.draft.json', 'build-args.json', 'MANUAL-EDITS.md', 'STATUS.md']:
        print('  ' + os.path.join(work, p))
    print('\nMeasurement (%d x %d px image):' % (img_w, img_h))
    print('  ' + measure_out.replace('\n', '\n  '))
    print('  scale x %.6f / z %.6f m/px, agreement %.2f%%%s' % (mx, mz, agree, '' if agree <= 2 else '  <-- CHECK'))
    print('  walls: outer %.3f m, interior %.3f m; %d outer, %d interior' % (
        OT, IT, len(spec['outerWalls']), len(spec['interiorWalls'])))
    print('  openings:')
    for wid, o in openings_list(spec):
        extra = o.get('swing') or o.get('note') or ''
        print('    %-8s %-20s %-7s %6.3f-%6.3f %s' % (wid, o['id'], o['type'], o['from'], o['to'], extra))
    print('  entrance: %s %s' % (entrance, '(footprint centre: no exterior door found)' if ent_todo
                                 else '(0.4 m inside %s)' % ent_door[1]))
    print('  review items:')
    for t in spec.get('review', []):
        print('    - ' + t)
    print('\nTODO:')
    for _, text in STATUS_ITEMS:
        print('  [ ] ' + text.format(id=a.id))
    for t in todos:
        print('      - ' + t)


# --------------------------------------------------------------------------- spec validation
def wall_rect(w, default_t):
    """[x1, z1, x2, z2] of a spec wall."""
    if 'line_z_outer' in w or 'line_x_outer' in w:
        if w['axis'] == 'x':
            z0, z1 = sorted((w['line_z_outer'], w['inner_z']))
            return [w['from'], z0, w['to'], z1], z1 - z0
        x0, x1 = sorted((w['line_x_outer'], w['inner_x']))
        return [x0, w['from'], x1, w['to']], x1 - x0
    t = w.get('thickness', default_t)
    if w['axis'] == 'x':
        c = w['center_z']
        return [w['from'], c - t / 2, w['to'], c + t / 2], t
    c = w['center_x']
    return [c - t / 2, w['from'], c + t / 2, w['to']], t


def angled_overlap(spec, w, poly):
    """How far a room polygon reaches into an angled wall (0 if it does not): the room is turned into
    the wall's frame, where the wall is the rectangle [0, length] x [band], and clipped to it. Outer
    walls run from their outside face line toward the footprint centre; interior walls are centred."""
    (ax, az), (bx, bz) = w['start'], w['end']
    length = math.hypot(bx - ax, bz - az)
    if length < 1e-9:
        return 0
    ux, uz = (bx - ax) / length, (bz - az) / length

    def local(x, z):
        dx, dz = x - ax, z - az
        return (dx * ux + dz * uz, -dx * uz + dz * ux)
    t = w['thickness']
    if w['kind'] == 'outer':
        cx, cz = spec['footprint'][0] / 2, spec['footprint'][1] / 2
        band = (0, t) if local(cx, cz)[1] > 0 else (-t, 0)
    else:
        band = (-t / 2, t / 2)
    pts = [local(x, z) for x, z in poly]
    overlaps = clip_rect(strips(pts), (0, band[0], length, band[1]))
    return max((min(max(p[0] for p in pc) - min(p[0] for p in pc), max(p[1] for p in pc) - min(p[1] for p in pc))
                for pc in overlaps), default=0)


def check_spec(spec, schema):
    """Return (errors, warnings)."""
    v = Validator(schema)
    v.check(spec, schema, '')
    errors = list(v.errors)
    warns = []
    if errors:
        return errors, warns
    W, D = spec['footprint']
    tol = 0.005
    if spec.get('draft'):
        warns.append('draft is still true: set it to false once reviewed.')
    if not spec.get('rooms'):
        errors.append('rooms is empty: fill rooms from the plan labels.')

    ids = {}

    def check_openings(w, lo, hi):
        for o in w['openings']:
            ids.setdefault(o['id'], []).append('opening')
            where = '%s/%s' % (w['id'], o['id'])
            if not o['from'] < o['to']:
                errors.append('%s: from %.3f must be < to %.3f' % (where, o['from'], o['to']))
            if o['from'] < lo - tol or o['to'] > hi + tol:
                errors.append('%s: %.3f-%.3f is outside its wall %.3f-%.3f' % (
                    where, o['from'], o['to'], lo, hi))
            if o['type'] == 'window' and not o['sill'] < o['head']:
                errors.append('%s: sill %.3f must be below head %.3f' % (where, o['sill'], o['head']))
            if o.get('head', 0) > spec['ceilingHeight'] + tol:
                errors.append('%s: head %.3f above the ceiling %.3f' % (where, o['head'], spec['ceilingHeight']))
            if o.get('needsReview'):
                warns.append('%s: needsReview is still set.' % where)
        ops = sorted(w['openings'], key=lambda o: o['from'])
        for p, q in zip(ops, ops[1:]):
            if q['from'] < p['to'] - tol:
                errors.append('%s: openings %s and %s overlap' % (w['id'], p['id'], q['id']))

    for w in spec['outerWalls'] + spec['interiorWalls']:
        ids.setdefault(w['id'], []).append('wall')
        check_openings(w, w['from'], w['to'])
        if not w['from'] < w['to']:
            errors.append('%s: wall from must be < to' % w['id'])
    for w in spec.get('angledWalls', []):
        ids.setdefault(w['id'], []).append('wall')
        length = math.hypot(w['end'][0] - w['start'][0], w['end'][1] - w['start'][1])
        if length < 0.1:
            errors.append('%s: angled wall is shorter than 0.1 m' % w['id'])
        for x, z in (w['start'], w['end']):
            if x < -tol or z < -tol or x > W + tol or z > D + tol:
                errors.append('%s: end [%.3f, %.3f] lies outside the footprint' % (w['id'], x, z))
        check_openings(w, 0, length)
    if spec.get('angledWalls') and not any(r.get('polygon') for r in spec.get('rooms', [])):
        warns.append('angledWalls are given but no room has a polygon: give the rooms they bound a polygon')
    for r in spec.get('rooms', []):
        ids.setdefault(r['id'], []).append('room')
    for k, kinds in ids.items():
        if len(kinds) > 1 and len(set(kinds)) == 1:
            errors.append('duplicate %s id "%s"' % (kinds[0], k))

    walls = [(w['id'],) + wall_rect(w, spec['wallThickness']['interior'])
             for w in spec['outerWalls'] + spec['interiorWalls']]
    rooms = []
    for r in spec.get('rooms', []):
        b = r.get('bounds')
        if not b:
            errors.append('room %s has no bounds [x1, z1, x2, z2]' % r['id'])
            continue
        x1, z1, x2, z2 = b
        if not (x1 < x2 and z1 < z2):
            errors.append('room %s bounds must have x1 < x2 and z1 < z2' % r['id'])
            continue
        if x1 < -tol or z1 < -tol or x2 > W + tol or z2 > D + tol:
            errors.append('room %s bounds lie outside the %.3f x %.3f footprint' % (r['id'], W, D))
        rooms.append((r['id'], b))
        for x, z in r.get('polygon') or []:
            if not (x1 - tol <= x <= x2 + tol and z1 - tol <= z <= z2 + tol):
                errors.append('room %s polygon point [%.3f, %.3f] lies outside its bounds' % (r['id'], x, z))
                break
        room_parts = strips(r['polygon']) if r.get('polygon') else None
        for aw in spec.get('angledWalls', []):
            depth = angled_overlap(spec, aw, r.get('polygon') or [[x1, z1], [x2, z1], [x2, z2], [x1, z2]])
            t = aw['thickness']
            if depth > t / 2 + 0.02:
                errors.append('room %s overlaps angled wall %s by %.3f m (more than half its %.3f m thickness): '
                              'its polygon should stop at the wall face' % (r['id'], aw['id'], depth, t))
            elif depth > 0.03:
                warns.append('room %s overlaps angled wall %s by %.3f m' % (r['id'], aw['id'], depth))
        for wid, (wx1, wz1, wx2, wz2), t in walls:
            ox = min(x2, wx2) - max(x1, wx1)
            oz = min(z2, wz2) - max(z1, wz1)
            if ox <= 0.02 or oz <= 0.02:
                continue
            depth = min(ox, oz)          # penetration across the wall's thickness (or a short stub)
            if room_parts is not None:
                overlaps = clip_rect(room_parts, (wx1, wz1, wx2, wz2))
                depth = max((min(max(p[0] for p in pc) - min(p[0] for p in pc),
                                 max(p[1] for p in pc) - min(p[1] for p in pc))
                             for pc in overlaps), default=0)
            if depth > t / 2 + 0.02:
                errors.append('room %s overlaps wall %s by %.3f m (more than half its %.3f m thickness): bounds '
                              'should stop at the wall face' % (r['id'], wid, depth, t))
            elif depth > 0.03:
                warns.append('room %s overlaps wall %s by %.3f m' % (r['id'], wid, depth))
    for i, (a, ba) in enumerate(rooms):
        for b, bb in rooms[i + 1:]:
            ox = min(ba[2], bb[2]) - max(ba[0], bb[0])
            oz = min(ba[3], bb[3]) - max(ba[1], bb[1])
            if ox > 0.05 and oz > 0.05:
                warns.append('rooms %s and %s overlap (%.2f x %.2f m)' % (a, b, ox, oz))
    for k, b in (spec.get('drawnItems') or {}).items():
        if not (b[0] < b[2] and b[1] < b[3]):
            errors.append('drawnItems %s must be [x1, z1, x2, z2] with x1 < x2 and z1 < z2' % k)
    return errors, warns


def run_check(work, quiet=False):
    path = os.path.join(work, 'spec.json')
    if not os.path.isfile(path):
        return None, ['spec.json not found in %s' % work], []
    try:
        spec = load_json(path)
    except ValueError as e:
        return None, ['spec.json is not valid JSON: %s' % e], []
    errors, warns = check_spec(spec, load_json(os.path.join(KIT, 'measure', 'spec.schema.json')))
    return spec, errors, warns


def cmd_check_spec(a):
    work = workdir_for(a, a.check_spec)
    spec, errors, warns = run_check(work)
    for w in warns:
        print('warning: ' + w)
    for e in errors:
        print('ERROR: ' + e)
    if errors:
        print('spec.json: %d error(s), %d warning(s)' % (len(errors), len(warns)))
        sys.exit(1)
    n_open = len(openings_list(spec))
    print('spec.json OK: %d outer walls, %d interior walls, %d openings, %d rooms, %d drawn items; %d warning(s)' % (
        len(spec['outerWalls']), len(spec['interiorWalls']), n_open, len(spec.get('rooms', [])),
        len(spec.get('drawnItems') or {}), len(warns)))


# --------------------------------------------------------------------------- status
def workdir_for(a, pid):
    root = os.path.abspath(os.path.expanduser(a.work_root))
    work = os.path.join(root, pid)
    if not os.path.isdir(work):
        die('no working directory %s (run new_property.py --plan ... --id %s first)' % (work, pid))
    return work


def cmd_status(a):
    work = workdir_for(a, a.status)
    pid = a.status
    ticked = set()
    sp = os.path.join(work, 'STATUS.md')
    if os.path.isfile(sp):
        with open(sp) as f:
            for line in f:
                m = re.match(r'- \[[xX]\] (.*)', line.strip())
                if m:
                    for key, text in STATUS_ITEMS:
                        if m.group(1).startswith(text.format(id=pid)[:30]):
                            ticked.add(key)
    done, notes = {}, {}

    spec, errors, warns = run_check(work)
    if spec is None:
        done['spec'], notes['spec'] = False, errors[0]
    else:
        done['spec'] = not errors
        notes['spec'] = ('valid, %d rooms, %d drawn items%s' % (
            len(spec.get('rooms', [])), len(spec.get('drawnItems') or {}),
            ', %d warning(s)' % len(warns) if warns else '') if not errors
            else '%d error(s), first: %s' % (len(errors), errors[0]))

    left = []
    pm = os.path.join(work, 'plan.md')
    if os.path.isfile(pm):
        with open(pm) as f:
            left = sorted(set(p for p in PH_RE.findall(f.read()) if p != 'PLACEHOLDER'))
    area_todos = []
    try:
        areas = load_json(os.path.join(work, 'areas.json'))
        area_todos = [x['key'] for x in areas.get('areas', []) if x.get('_todo')]
    except (OSError, ValueError):
        areas = {'areas': []}
    done['plan'] = not left and not area_todos
    notes['plan'] = 'plan.md placeholders left: %d; areas with _todo: %s' % (len(left), ', '.join(area_todos) or 'none')

    try:
        args = load_json(os.path.join(work, 'build-args.json'))
    except (OSError, ValueError):
        args = {}
    rev = args.get('startRevision')
    done['create'] = isinstance(rev, int) and not isinstance(rev, bool)
    notes['create'] = 'startRevision %s; rooms.json %s' % (
        rev, 'present' if os.path.isfile(os.path.join(work, 'rooms.json')) else 'missing')
    if done['create'] and args.get('areas') != areas:
        notes['create'] += '; build-args.json areas differ from areas.json'

    done['viewer'] = 'viewer' in ticked or done['create'] and 'build' in ticked
    notes['viewer'] = 'manual: tick it in STATUS.md' if not done['viewer'] else 'ticked'

    keys = [x['key'] for x in areas.get('areas', [])]
    have = [k for k in keys if os.path.isdir(os.path.join(work, 'payloads', k)) and
            any(n.endswith('.json') for n in os.listdir(os.path.join(work, 'payloads', k)))]
    final = os.path.isfile(os.path.join(work, 'validation', 'final.json'))
    done['build'] = final and len(have) == len(keys) and 'build' in ticked
    notes['build'] = 'payloads for %d/%d areas%s; validation/final.json %s%s' % (
        len(have), len(keys), (' (missing: %s)' % ', '.join(k for k in keys if k not in have)) if len(have) < len(keys)
        else '', 'present' if final else 'missing',
        '; walkthrough/VR/extraction: tick in STATUS.md' if final and 'build' not in ticked else '')

    print('%s: %s' % (pid, work))
    nxt = None
    for key, text in STATUS_ITEMS:
        print('[%s] %s\n      %s' % ('x' if done[key] else ' ', text.format(id=pid), notes[key]))
        if not done[key] and nxt is None:
            nxt = text.format(id=pid)
    if left:
        print('plan.md placeholders: ' + ', '.join('{{%s}}' % p for p in left))
    print('\nNext: ' + (nxt or 'all done'))


# --------------------------------------------------------------------------- main
def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    mode = ap.add_mutually_exclusive_group(required=True)
    mode.add_argument('--id', help='new property id (3-60 lowercase letters, numbers, single hyphens)')
    mode.add_argument('--status', metavar='PROPERTY_ID', help='report which steps are done and the next one')
    mode.add_argument('--check-spec', metavar='PROPERTY_ID', help='validate <workDir>/spec.json')
    ap.add_argument('--plan', help='floor-plan image (PNG/JPEG)')
    ap.add_argument('--name', help='display name')
    ap.add_argument('--width-ft', type=float, help='labelled outside width (plan x) in feet')
    ap.add_argument('--depth-ft', type=float, help='labelled outside depth (plan y) in feet')
    ap.add_argument('--width-m', type=float, help='labelled outside width (plan x) in metres')
    ap.add_argument('--depth-m', type=float, help='labelled outside depth (plan y) in metres')
    ap.add_argument('--work-root', default=DEFAULT_ROOT, help='durable root for working dirs (default %(default)s)')
    ap.add_argument('--ceiling', type=float, default=2.44, help='ceiling height in metres (default %(default)s)')
    ap.add_argument('--market', default='USA, USD, US retailers', help='market for product research')
    ap.add_argument('--currency', default='USD', help='ISO currency code (default %(default)s)')
    ap.add_argument('--style', help='"exterior ...; interior ..."')
    ap.add_argument('--storeys', type=int, default=1, help='storeys (the measurer reads one; default 1)')
    ap.add_argument('--crop', help='x0,y0,x1,y1 plan region (original pixels) to measure')
    ap.add_argument('--force', action='store_true', help='regenerate into an existing working directory')
    a = ap.parse_args(argv)
    if a.status or a.check_spec:
        durable_or_die(os.path.abspath(os.path.expanduser(a.work_root)))
    if a.status:
        cmd_status(a)
    elif a.check_spec:
        cmd_check_spec(a)
    else:
        if not re.match(r'^[A-Z]{3}$', a.currency):
            die('--currency must be a 3-letter ISO code such as USD')
        cmd_init(a)


if __name__ == '__main__':
    main()
